title: Vedat Kamer
email: vkamer@istanbul.edu.tr
description: İstanbul Üniversitesi Edebiyat Fakültesi Felsefe Bölümü Mantık Anabilim Dalı Öğretim Üyesi
theme: minima
url: "https://vedatkamer.com.tr"
twitter_username: VedatKamer
github_username:  VedatKamer
