title: Vedat Kamer
email: vkamer@istanbul.edu.tr
description: Assistant Professor at Istanbul University, Faculty of Letters, Department of Philosophy, Department of Logic.
url: "https://vedatkamer.com.tr"
twitter_username: VedatKamer
github_username:  VedatKamer
